### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by nyotis** [LumaPictures/arnold-rv#1]
thanks for uploading the source:
1. I build the makefile in /me/dev/arnold-rv-master/driver and i get an extra /disk1/nik-y/playpen/dev/arnold-rv/driver4.1. directory containing rvdriver.so. I get two extra copies of rvdriver.so: one in /disk1/nik-y/playpen/dev/arnold-rv/driver/build and the other in /disk1/nik-y/playpen/dev/arnold-rv/driver/build/4.1.

Is this normal? or it's related to my distro/set-up environment?
1. rv isn't picked up, the complete log is below

00:00:00     5MB         | log started Wed Mar  5 17:48:25 2014
00:00:00     5MB         | Arnold 4.1.3.3 linux icc130 glibc25 libstdc++348 oiio10202 rlm1012 2014/01/13 16:38:26
00:00:00     5MB         | running on escape2.blue-bolt.local
00:00:00     5MB         |  2 x Intel(R) Xeon(R) CPU E5620 @ 2.40GHz (8 cores, 8 logical) with 11889MB
00:00:00     5MB         |  CentOS 6.4 (Final), Linux kernel 2.6.32-358.el6.xyou get the two warnings below86_64
00:00:00     5MB         |  
00:00:00     5MB         | [kick] command: /software/arnold/linux.centos6.x86_64/4.1.3.3/bin/kick test.ass -log
00:00:00     5MB WARNING | skipping nonexisting shader path: /software/aaOcean/linux.centos6.x86_64/2.5/arnold/4.1
00:00:00     5MB         | loading plugins from /software/cortex/linux.centos6.x86_64/8.0.0b3/arnoldProcedurals ...
00:00:00    41MB         | no plugins loaded
00:00:00    41MB         | loading plugins from /software/cortex/linux.centos6.x86_64/8.0.0b3/arnoldOutputDrivers ...
00:00:00    41MB         | loaded 1 plugins from 1 lib(s) in 0:00.00
00:00:00    41MB         | loading plugins from /software/mtoa/linux.centos6.x86_64/1.0.0.1//2014/shaders ...
00:00:00    41MB         | loaded 86 plugins from 1 lib(s) in 0:00.00
00:00:00    41MB WARNING | skipping nonexisting shader path: /software/bashaders/linux.centos6.x86_64/25.01.09/arnold/4.1
00:00:00    41MB         | loading plugins from /software/alshaders/linux.centos6.x86_64/0.3.3/arnold/4.1 ...
00:00:00    42MB         | loaded 17 plugins from 17 lib(s) in 0:00.01
00:00:00    42MB         | loading plugins from /software/bluebolt/tools/bb_projection/linux.centos6.x86_64/1.1.2/arnold/4.1 ...
00:00:00    42MB         | loaded 2 plugins from 1 lib(s) in 0:00.00
00:00:00    42MB WARNING | skipping nonexisting shader path: /nethome/nik-y/tools/arnold/linux.centos6.x86_64/4.1/shaders
00:00:00    42MB WARNING | skipping nonexisting shader path: /software/tools/arnold/linux.centos6.x86_64/4.1/shaders
00:00:00    42MB WARNING | skipping nonexisting shader path: /software/bluebolt/tools/arnold/linux.centos6.x86_64/4.1/shaders
00:00:00    42MB WARNING | too many messages (>5) of type: "skipping nonexisting shader path: %s" -- not printing any more!
00:00:00    42MB         | loading plugins from /software/alembic/linux.centos6.x86_64/1.5.0.1/arnold/ ...
00:00:00    42MB         | no plugins loaded
00:00:00    42MB         | loading plugins from . ...
00:00:00    42MB         | no plugins loaded
00:00:00    42MB         | [ass] loading test.ass ...
00:00:00    43MB WARNING |  [ass] line 19: options.sss_subpixel_cache: unknown 'sss_subpixel_cache' parameter
00:00:00    43MB WARNING |  [ass] line 23: options.binary_ass: unknown 'binary_ass' parameter
00:00:00    43MB WARNING |  [ass] line 40: node "driver_rv" is not installed
00:00:00    43MB         | [ass] read 55327 bytes, 9 nodes in 0:00.00
00:00:00    43MB         |  
00:00:00    43MB         | [rlm] checkout of arnold (version 20140113) from pepe.blue-bolt.local OK
00:00:00    44MB         |  
00:00:00    44MB         | there are 1 light and 1 object:
00:00:00    44MB         |  1 polymesh
00:00:00    44MB         |  
00:00:00    44MB         | rendering image at 1024 x 1024, -3 AA samples, 2 GI samples, 1 GI bounces
00:00:00    44MB         |  initializing 13 nodes ...
00:00:00    44MB         |  node initialization done in 0:00.00
00:00:00    45MB         |  creating root object list ...
00:00:00    45MB         |   scene bounds: (-3.00000072 -3 -3.00000143) -> (3 3 3.00000048)
00:00:00    45MB         |  updating 14 nodes ...
00:00:00    45MB         |  node update done in 0:00.00
00:00:00    45MB         |  [aov] registered driver: "kick_display" (driver_x11)
00:00:00    45MB         |  [aov]  \* "RGBA" of type RGBA filtered by "kick_display_filter" (gaussian_filter)
00:00:00    63MB         |  [aov] done preparing 1 AOV for 1 output to 1 driver (0 deep AOVs)
00:00:00    63MB         |  starting 8 bucket workers of size 64x64 ...
00:00:00    64MB         |  bucket workers done in 0:00.14
00:00:00    64MB         | render done
00:00:00    64MB         |  
00:00:00    64MB         | rendering image at 1024 x 1024, -2 AA samples, 2 GI samples, 1 GI bounces
00:00:00    64MB         |  updating 14 nodes ...
00:00:00    64MB         |  node update done in 0:00.00
00:00:00    64MB         |  [aov] registered driver: "kick_display" (driver_x11)
00:00:00    64MB         |  [aov]  \* "RGBA" of type RGBA filtered by "kick_display_filter" (gaussian_filter)
00:00:00    64MB         |  [aov] done preparing 1 AOV for 1 output to 1 driver (0 deep AOVs)
00:00:00    64MB         |  starting 8 bucket workers of size 64x64 ...
00:00:00    64MB         |  bucket workers done in 0:00.12
00:00:00    64MB         | render doneyou get the two warnings below
00:00:00    64MB         |  
00:00:00    64MB         | rendering image at 1024 x 1024, -1 AA samples, 2 GI samples, 1 GI bounces
00:00:00    64MB         |  updating 14 nodes ...
00:00:00    64MB         |  node update done in 0:00.00
00:00:00    64MB         |  [aov] registered driver: "kick_display" (driver_x11)
00:00:00    64MB         |  [aov]  \* "RGBA" of type RGBA filtered by "kick_display_filter" (gaussian_filter)
00:00:00    64MB         |  [aov] done preparing 1 AOV for 1 output to 1 driver (0 deep AOVs)
00:00:00    64MB         |  starting 8 bucket workers of size 64x64 ...
00:00:01    65MB         |  bucket workers done in 0:00.26
00:00:01    65MB         | render done
00:00:01    65MB         |  
00:00:01    65MB         | rendering image at 1024 x 1024, 1 AA samples, 2 GI samples, 1 GI bounces
00:00:01    65MB         |  updating 14 nodes ...
00:00:01    65MB         |  node update done in 0:00.00
00:00:01    65MB         |  [aov] registered driver: "kick_display" (driver_x11)
00:00:01    65MB         |  [aov]  \* "RGBA" of type RGBA filtered by "kick_display_filter" (gaussian_filter)
00:00:01    65MB         |  [aov] done preparing 1 AOV for 1 output to 1 driver (0 deep AOVs)
00:00:01    65MB         |  starting 8 bucket workers of size 64x64 ...
00:00:01    65MB         |  bucket workers done in 0:00.96
00:00:01    65MB         | render done
00:00:01    65MB         |  
00:00:01    65MB         | rendering image at 1024 x 1024, 6 AA samples, 2 GI samples, 1 GI bounces
00:00:01    65MB         |  updating 14 nodes ...
00:00:01    65MB         |  node update done in 0:00.00
00:00:01    65MB ERROR   |  [aov] output references a non-driver node: driver_rv
00:00:01    65MB ERROR   |  [aov] output references a non-driver node: driver_rv
00:00:01    65MB ERROR   |  [aov] output references a nyou get the two warnings belowon-driver node: driver_rv
00:00:01    65MB         |  [aov] registered driver: "kick_display" (driver_x11)
00:00:01    65MB         |  [aov]  \* "RGBA" of type RGBA filtered by "kick_display_filter" (gaussian_filter)
00:00:01    65MB         |  [aov] done preparing 1 AOV for 1 output to 1 driver (0 deep AOVs)
00:00:01    65MB WARNING |  failed to launch bucket workers:  received abort signal
00:00:01    65MB         | render done
00:00:01    65MB         |  
00:00:01    65MB         | releasing resources
00:00:01    65MB         | Arnold shutdown

Compiled on
Target: x86_64-redhat-linux
gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC)

with these warnings:
rvdriver.cpp:34: warning: ‘bool DriverNeedsBucket(AtNode_, int, int, int, int, int)’ used but never defined
rvdriver.cpp:34: warning: ‘void DriverProcessBucket(AtNode_, AtOutputIterator_, AtAOVSampleIterator_, int, int, int, int, int)’ used but never defined

**Comment by nyotis** [comment]
since the rv "driver" is not running, it is highly unlikely that RV is causing the problem. I am digging into your code + makefile to find out what's wrong

**Comment by chadrik** [comment]
I'm assuming you added `rv_driver.so` to your `ARNOLD_PLUGIN_PATH`?  Also, I see a lot of ""skipping nonexisting shader path" so make sure your paths are setup correctly.

**Comment by nyotis** [comment]
Correct: library is added to the Arnold plugin path. Will check path and update you later on, cheers!

**Comment by nyotis** [comment]
quoting solidangle support
"The real problem is that this pre-4.1 driver is missing the DriverNeedsBucket() and DriverProcessBucket() methods, which are now mandatory in latest Arnold."

will update you once successfully load your code
